### ISSUE TITLE
Package shows error in yml file 

### ISSUE THREAD

**Issue by shashi-appgolive** [damienaicheh/azure-devops-mobile-versioning#15]
<img width="830" alt="Screenshot 2022-05-02 at 6 56 24 PM" src="https://user-images.githubusercontent.com/64683815/166241295-2bdaa44f-1017-475c-9378-9724422666ba.png">
<img width="970" alt="Screenshot 2022-05-02 at 6 57 16 PM" src="https://user-images.githubusercontent.com/64683815/166241400-477c9c47-c550-42e7-a89c-f121dce936ec.png">

**Comment by damienaicheh** [comment]
It's probably one of your extensions which is probably to strict. We never see this issue in our projects. Without more explanation I will close the issue.
