### ISSUE TITLE
DevOps Server Support

### ISSUE THREAD

**Issue by ac87** [damienaicheh/azure-devops-mobile-versioning#2]
After manually installing the extension into DevOps Server 2019 Update 1.1 the extension doesn't appear installed and nor do the tasks when added to a YAML build.

![image](https://user-images.githubusercontent.com/20557626/95085464-2c12bd80-0717-11eb-834f-565f545add1c.png)

But it can be seen on the manage page
![image](https://user-images.githubusercontent.com/20557626/95085580-52385d80-0717-11eb-897d-389835dbf1c0.png)

Does this extension not work on DevOps Server or is this a bug/user error? 

Thanks

**Comment by damienaicheh** [comment]
Hello, I don't know any restriction about this, it's strange

**Comment by ac87** [comment]
I'm an idiot, after uploading the .vsix the extension isn't installed. 

You then have to click it, go to a local version of the extension info page and click 'Get it free'. This then prompts to actually install it.

![image](https://user-images.githubusercontent.com/20557626/95121024-5b8cee80-0746-11eb-9876-5c3892534a9a.png)

I had a feeling it was user error. had no idea the get it free button means install. It's not obvious. It is obvious I'm new to this!

**Comment by damienaicheh** [comment]
No problem, happy to see that you fixed your issue :)
