### ISSUE TITLE
Commit Count and Version Count Reset

### ISSUE THREAD

**Issue by danwize** [damienaicheh/azure-devops-mobile-versioning#20]
We recently moved our code to a new repository in azure devops (moving it all to a new devops project).  Now, when I run ExtractVersionFromTag@1 the NUMBER_OF_COMMITS value is back to 1 (it was over 500) and it is not able to extract the version number.

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/29284872/209163692-459789f1-ec9e-4318-ad19-0576b35908a8.png">

There was an error extracting the version number from tags, even though I can clearly see that all my git history was retained in the move.  Once I added a new tag, the version number was extracted successfully.  I checked out the code from the new repo and ran the command 
`git describe --tags --abbr=0`

This did return the latest tag: 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/29284872/209164375-ad7b3b59-6cb0-4328-a867-65f95c2414d4.png">

Likewise, the commad to get the commit count worked locally:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/29284872/209164623-92452a24-361a-4520-93ab-e52a70c4e104.png">

I'm suspecting that the git command that runs in extract-version-from-tag.ts is running some azure command rather than an actual git command?  Perhaps azure is not returning the commit count from the git repository, but rather from some count that is updated in azure whenever there is a commit?

**Comment by damienaicheh** [comment]
This task only run git command, nothing more. I suppose something went wrong when moving the repositories in Azure DevOps. Did you move the entire history and pushed all the tags?

**Comment by danwize** [comment]
yes.  I have the entire history and tags.  When I ran the git commands locally I got the values I expected.  Even though all the tags show up in azure devops, the ExtractVersionFromTag@1 task didn't successfully extract tags until I added one more new one:

![image](https://user-images.githubusercontent.com/29284872/209168129-9692b236-5289-4c86-baf7-2ffcfaae035a.png)

I'm adding some echo statements to my pipeline to see if I can get a better idea of what is going on.

**Comment by danwize** [comment]
Not sure why head count is different when I run this in azure:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/29284872/209172631-c4c491ac-4ad6-4d76-a2c4-d38c0cba8150.png">

`# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android
name: worker_safety_android_$(SourceBranchName)_$(Date:yyyyMMdd-HHmmss)$(Rev:.r)


trigger:
  tags:
    include:
      - 3.*

pool:
  vmImage: 'macos-latest'

steps:

  - script: |
      echo "curent location"
      pwd
      echo "where is git"
      which git
      echo "what is in here"
      ls
      echo "run some git command"
      git rev-list --count "HEAD"`

Here are the results when I run locally:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/29284872/209173229-b03a8e02-fcb7-4757-b97d-c4dbe07d78f0.png">

**Comment by danwize** [comment]
possibly something to do with fetch depth:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/29284872/209187385-8c743e1e-40ed-46a8-b26d-67e49a04d516.png">

https://stackoverflow.com/questions/6802145/how-to-convert-a-git-shallow-clone-to-a-full-clone

**Comment by damienaicheh** [comment]
Yes I know the issue! Got o your pipeline settings and you have an option with the keyword "shallow" at the bottom of the page. There was an update a few weeks ago and it's activated by default. Just uncheck it and all the history of your git repository will be checkout

**Comment by danwize** [comment]
I just found this article that confirms what you said about shallow fetch being activated by default for new pipelines:

https://dev.to/kkazala/azure-devops-pipelines-shallow-fetch-1-is-now-default-4656

**Comment by danwize** [comment]
I didn't find the pipeline settings you were talking about.  Maybe that is because I'm using the yml pipelines rather than legacy.  To fix this issue I had to explicitly add the checkout step to my yml rather than rely on the automatic checkout inherent in the pipeline.  I just had to add this to my steps section:

`- checkout: self
  fetchDepth: 0
  clean: true`
  
  so, my pipeline now looks like this:
  
  `name: worker_safety_android_$(SourceBranchName)_$(Date:yyyyMMdd-HHmmss)$(Rev:.r)


trigger:
  tags:
    include:
      - 3.*

pool:
  vmImage: 'macos-latest'

steps:

- checkout: self
  fetchDepth: 0
  clean: true

- task: ExtractVersionFromTag@1
  
- script: |
    echo "curent location"
    pwd
    echo "where is git"
    which git
    echo "what is in here"
    ls
    echo "run some git command"
    git rev-list --count "HEAD"
    echo "number of commits $(NUMBER_OF_COMMITS)"`
    
    Here is a link to the documentation:
    https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#shallow-fetch

**Comment by damienaicheh** [comment]
You need to select a pipeline > edit > click on the 3 dots > triggers > in the YAML tab > click source

@danwize Here a screenshot:

<img width="1227" alt="Capture d’écran 2022-12-23 à 09 11 20" src="https://user-images.githubusercontent.com/38168153/209298868-54703d5a-bb5b-4da4-80a2-10661b7f9827.png">
