### ISSUE TITLE
UpdateAndroidVersionGradle not available?

### ISSUE THREAD

**Issue by techker** [damienaicheh/azure-devops-mobile-versioning#21]
Installed the extension and seen it added 2 settings For manifest and Version in manifest but did not see the update Gradle task?

is it missing?or need to activate something else?

when i add the task from your example it gives me not found?

i need to change the build number and version name.
- task: UpdateAndroidVersionGradle@1
  inputs:
    buildGradlePath: 'AndroidGradleVersionProject/app/build.gradle'

**Comment by damienaicheh** [comment]
I let you see my article about it, you will find all the option here:

https://damienaicheh.github.io/azure/devops/2019/12/19/manage-your-application-version-automatically-using-git-and-azure-devops-en
