### ISSUE TITLE
end-of-life node version for hosted agents

### ISSUE THREAD

**Issue by cyptus** [damienaicheh/azure-devops-mobile-versioning#37]
UpdateiOSVersionInfoPlist@1 warns with:

`##[warning]Task 'Update iOS version Info.plist' version 1 (UpdateiOSVersionInfoPlist@1) is dependent on a Node version (6) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
`

**Comment by aquam8** [comment]
I have a similar warning with `ExtractVersionFromTag`.

See the error:
```
Downloading task: ExtractVersionFromTag (1.3.0)
##[warning]Task 'Extract Version' version 1 (ExtractVersionFromTag@1) is dependent on a Node version (6) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```

Thank you for your support

**Comment by TraGicCode** [comment]
Hey @damienaicheh ,

I have the same issue.

```
##[warning]Task 'Update iOS version Info.plist' version 1 (UpdateiOSVersionInfoPlist@1) is dependent on a Node version (6) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```

Can you please update this repository just like you did for your github actions repository?

**Comment by damienaicheh** [comment]
Hello, I think I found what I have to do, I will try to do it this month

**Comment by damienaicheh** [comment]
Update done.
