### ISSUE TITLE
Is Kotlin-Script (.kts) supported?

### ISSUE THREAD

**Issue by JanZeman** [damienaicheh/azure-devops-mobile-versioning#7]
Hello, I probably did not invest enough time and might be wrong in my conclusion...

I tried to use UpdateAndroidVersionGradleTask. It passes, all is green, but no real effect. Looked at the task source code and my guess is that the reason if fails for me is because we use .kts. The syntax difference is "versionCode = 1" instead of the traditional "versionCode 1". It seems the **regular expression** "/versionCode\s*(\d+(?:\.\d)*)/mg" does not catch this case.

I have 2 questions:
- Could I be correct in my conclution?
- If yes, would it be difficult to add the .kts support? Would it mean just modifying of this regular expression(s) or would more effort be necessary?

**Comment by damienaicheh** [comment]
Hello,

Yes correct, it's just the regular expression. 
Send me a file as an example and the correct regular expression that match both cases and if it works I will add it. You can also do a pull request directly. I will look at it as soon as possible.

**Comment by JanZeman** [comment]
Hi Damien, my apologies for the silence. Being bit in a time press I turned out that for our case it was easier / faster to have a simple .sh script in our repo in contrary to search of rather very generic solution that would be required here. If I bump into this problematic again I hope I will be able to contribute more.

**Comment by damienaicheh** [comment]
No problem @JanZeman  Thanks for the feedback!
