### ISSUE TITLE
This task uses Node 6 execution handler, which will be deprecated soon message

### ISSUE THREAD

**Issue by neoswallow** [damienaicheh/azure-devops-mobile-versioning#8]
I got following message from the last build.

##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

I was using UpdateAndroidVersionGradleTask@1 task.

Url for the migration to Node10 guideline.
https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode10.md

**Comment by damienaicheh** [comment]
Thanks for the feedback I will look at it as soon as possible

**Comment by damienaicheh** [comment]
Hi, It's updated. Available on version 1.1.0. Have a nice day.

**Comment by neoswallow** [comment]
A question.
Even though latest version here is 1.0.6 (now 1.1.0, thanks for the quick update 👍🏼), Azure log says it's running 1.0.1.
I was using `- task: UpdateAndroidVersionGradle@1`

**Comment by damienaicheh** [comment]
You have some cache. Force refresh the page.

**Comment by neoswallow** [comment]
I meant actual Azure pipelines task log.
```
Starting: UpdateAndroidVersionGradle
==============================================================================
Task         : Update gradle version for Android
Description  : Learn more about this task by looking to the [Github repository]()
Version      : 1.0.1
Author       : Damien Aicheh
Help         : 
==============================================================================
##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.
Finishing: UpdateAndroidVersionGradle
```

**Comment by damienaicheh** [comment]
You are not running the last one. Remove the extension and reinstall it.

**Comment by neoswallow** [comment]
I'll try that. Thanks.

**Comment by neoswallow** [comment]
Yup. That did it.
```
Starting: UpdateAndroidVersionGradle
==============================================================================
Task         : Update gradle version for Android
Description  : Update gradle version for Android
Version      : 1.1.0
Author       : Damien Aicheh
Help         : 
==============================================================================
Finishing: UpdateAndroidVersionGradle
```
Thank you 👍🏼👍🏼
